### ISSUE TITLE
Remove Version Info from an Executable file

### ISSUE THREAD

**Issue by developer191** [jet2jet/resedit-js-cli#34]
Is it possible to remove "Version Info" from an executable file?
i tried with an empty version definition like below:
```yaml
lang: 1033
version:
  comments: ""
  companyName: ""
  fileDescription: ""
  fileVersion: "" # i also tried: fileVersion: " "
  internalName: ""
  legalCopyright: ""
  legalTrademarks: ""
  originalFileName: ""
  privateBuild: ""
  productName: ""
  productVersion: ""
  specialBuild: ""
  # extraValues: ?? what is an empty object definition in Typescript? (I'm not a JS guy 😇)
```
but "File version" property in file remains untouched.
is there any way to completely remove "Version Info" from an existing executable file with this useful tool?
